const productsQ = [
  {
    id: 1,
    name: "Apple BYZ S8521",
    price: 2927,
    rating: 4.7,
    image: "/Image.png",
    wire: false,
  },
  {
    id: 2,
    name: "Apple EarPods",
    price: 2327,
    rating: 4.5,
    image: "/Image1.png",
    wire: false,
  },
  {
    id: 3,
    name: "Apple EarPods",
    price: 2327,
    rating: 4.5,
    image: "/Image2.png",
    wire: false,
  },
  {
    id: 4,
    name: "Apple BYZ S8521",
    price: 2927,
    rating: 4.7,
    image: "/Image.png",
    wire: false,
  },
  {
    id: 5,
    name: "Apple EarPods",
    price: 2327,
    rating: 4.5,
    image: "/Image1.png",
    wire: false,
  },
  {
    id: 6,
    name: "Apple EarPods",
    price: 2327,
    rating: 4.5,
    image: "/Image2.png",
    wire: false,
  },
  {
    id: 7,
    name: "Apple AirPods",
    price: 9527,
    rating: 4.7,
    image: "/Image3.png",
    wire: true,
  },
  {
    id: 8,
    name: "GERLAX GH-04",
    price: 6527,
    rating: 4.7,
    image: "/Image4.png",
    wire: true,
  },
  {
    id: 9,
    name: "Apple EarPods",
    price: 7527,
    rating: 4.7,
    image: "/Image5.png",
    wire: true,
  },
];

export default productsQ;
